[build]
command = "yarn build --environment=staging"
environment = { NODE_VERSION = "12.22.1" }

[context.master]
command = "yarn build --environment=production"
environment = { NODE_VERSION = "12.22.1" }
