# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
        environment:
            CHROME_BIN: "/usr/bin/google-chrome"
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - run: sudo yarn global add bower
      
      - run: bower install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

      # deploy
      - run:
          name: Avoid hosts unknown for github
          command: ssh-keyscan planninglabs.nyc >> ~/.ssh/known_hosts
      - deploy:
          name: Deployment
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn build -e production
              cd dist
              touch .static
              git init
              git add .
              git -c user.name='Labs Deploy Script' -c user.email='labs_dl@planning.nyc.gov' commit -m "deploy"
              git remote add dokku dokku@planninglabs.nyc:regional-viz && git push -f dokku master
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
              yarn build -e staging
              cd dist
              touch .static
              git init
              git add .
              git -c user.name='Labs Deploy Script' -c user.email='labs_dl@planning.nyc.gov' commit -m "deploy"
              git remote add dokku dokku@planninglabs.nyc:regional-viz-staging && git push -f dokku master
            fi
