---
narratives:
- slug: jobs-narrative-1
  title: Amazon to come here!
  category: jobs
  description: |
    # Into the Woods

    Once upon a time
    In a far-off kingdom
    There lay a small village
    At the edge of the woods
    I wish
    And in this village
    More than anything
    Lived a young maiden

  map: a-region-region
- slug: people-narrative-2
  category: people
  title: JObs everywhere!
  map: transit-oriented-viz
- slug: housing-narrative-3
  category: housing
  title: Housing Productivity
  map: transit-oriented-viz
- slug: jobs-narrative-4
  title: There are more ppl working!!
  category: jobs
  map: a-region-region
- slug: people-narrative-5
  category: people
  title: JObs everywhere!
  map: transit-oriented-viz
- slug: housing-narrative-6
  category: housing
  title: Housing Productivity
  map: transit-oriented-viz
maps:
- slug: population-change
  title: Population Change 2010-2016
  sources:
  - id: population-change
    type: cartovector
    source-layers:
    - id: population-change-counties
      sql: >
        SELECT a.the_geom_webmercator, a.name, b.popp1016 FROM region_counties_v0 a
        LEFT JOIN region_counties_attributes_v0 b
        ON a.geoid = to_char(b.stcoid, 'FM00000')
  layers:
  - id: population-change-counties
    type: choropleth
    source: population-change
    source-layer: population-change-counties
    paintConfig:
      opacity: 0.6
      property: popp1016
      colors:
      - "#d76423"
      - "#ffa555"
      - "#ffffe0"
      - "#b3e4ff"
      - "#5ab4ff"
      - "#004da8"
      breaks:
      - -0.025
      - -0.01
      - .01
      - .025
      - .05
      - 1
- slug: transit-oriented-viz
  title: Transit Oriented Viz
  sources:
  - id: transit-oriented
    type: cartovector
    source-layers:
    - id: transit-oriented-subway
      sql: SELECT the_geom_webmercator FROM support_trans_mta_subway_routes
  layers: []
