orderings:

  pages:
    - id: about

  maps:
    - id: intro
      hasNarrative: true
      hideFromMenu: true

    - id: foreign-born
      hasNarrative: true

    - id: net-population-change
      hasNarrative: true

    - id: population-change
      hasNarrative: true

    - id: population-density
      hasNarrative: true

    - id: prime-labor-force-gain
      hasNarrative: true

    - id: total-population
      hasNarrative: true

    - id: total-employment
      hasNarrative: true

    - id: total-units-permitted
      hasNarrative: true

    - id: total-units
      hasNarrative: true
