orderings:

  pages:
    - id: about

  maps:
    - id: intro
      hasNarrative: true
      hideFromMenu: true

    - id: housing-1
      hasNarrative: true

    - id: housing-units-permitted
      hasNarrative: true

    - id: housing-2
      hasNarrative: false

    - id: private-employment-change
      hasNarrative: true

    - id: jobs-2
      hasNarrative: true

    - id: people-2
      hasNarrative: true

    - id: population-change
      hasNarrative: true

    - id: population-change-subregion
      hasNarrative: false
