orderings:

  pages:
    - id: about

  maps:
    - id: intro
      isLinearNarrative: true
      hideFromMenu: true
      transitionPrompt: 23.5 million people live in the NYC region...

    # People
    - id: total-population
      isLinearNarrative: true
      transitionPrompt: Our region is densest at the center...
    - id: population-density
      isLinearNarrative: true
      transitionPrompt: Population growth has shifted towards the center...
    - id: population-change
      isLinearNarrative: true
      transitionPrompt: Population growth has shifted towards the center...
    - id: pct-population-change
      isLinearNarrative: true
      transitionPrompt: Growing areas are among the most diverse...
    - id: foreign-born
      isLinearNarrative: true
      transitionPrompt: Growing areas are among the most diverse...
    - id: population-race-2010
      isLinearNarrative: true
      transitionPrompt: Growing areas are among the most diverse...
    - id: population-race-2020
      isLinearNarrative: true
      transitionPrompt: The region's labor force is growing...
    - id: labor-force-change
      isLinearNarrative: true
      transitionPrompt: Labor force age 25-54 grew mostly at the center...
    - id: prime-labor-force-change
      isLinearNarrative: true
      transitionPrompt: Our region's labor force is aging...
    - id: aging-labor-force-change
      isLinearNarrative: true
      transitionPrompt: Our region has 9.1 million homes...

    # Housing
    - id: total-units
      isLinearNarrative: true
      transitionPrompt: Rental housing is concentrated in NYC...
    - id: renter-owner
      isLinearNarrative: true
      transitionPrompt: Multifamily housing is concentrated in NYC...
    - id: units-structure-size
      isLinearNarrative: true
      transitionPrompt: NYC and NJ are building the majority of new housing...
    - id: units-permitted
      isLinearNarrative: true
      transitionPrompt: Most new housing was in multifamily buildings...
    - id: units-permitted-size
      isLinearNarrative: true
      transitionPrompt: NYC is the hub of the largest U.S. metro economy...

    # Jobs
    - id: employment-total
      isLinearNarrative: true
      transitionPrompt: The region has a robust and diverse job base...
    - id: employment-by-sector
      isLinearNarrative: true
      transitionPrompt: NYC generates half of the region's economic output...
    - id: gdp-total
      isLinearNarrative: true
      transitionPrompt: Half of the region's office jobs are in NYC...
    - id: office-employment
      isLinearNarrative: true
      transitionPrompt: There are 2.2 million institutional jobs in the region...
    - id: institutional-employment
      isLinearNarrative: true
      transitionPrompt: There are 1.7 million industrial jobs in the region...
    - id: industrial-employment
      isLinearNarrative: true
      transitionPrompt: 2.6 million retail & hospitality jobs in the region...
    - id: localserve-employment
      isLinearNarrative: true
      transitionPrompt: NYC captured most of the region's job growth...
    - id: private-employment-change
      isLinearNarrative: true
      transitionPrompt: NYC grew GDP five times faster than the region...
    - id: gdp-pctchange
      isLinearNarrative: true
      transitionPrompt: NYC office job growth offset regional losses...
    - id: office-employment-change
      isLinearNarrative: true
      transitionPrompt: Institutional jobs grew the most of any sector...
    - id: institutional-employment-change
      isLinearNarrative: true
      transitionPrompt: The region continued to lose industrial jobs...
    - id: industrial-employment-change
      isLinearNarrative: true
      transitionPrompt: Local services buoyed the post-recession economy...
    - id: localserve-employment-change
      isLinearNarrative: true
      transitionPrompt: The regional housing-jobs balance has shifted...

    # Balance
    - id: housjobs00
      isLinearNarrative: true
      transitionPrompt: The regional housing-jobs balance has shifted...
    - id: housjobs20
      isLinearNarrative: true
      transitionPrompt: The regional housing-jobs balance has shifted...
    - id: housjobs0020
      isLinearNarrative: true
      transitionPrompt: 20% of 4.7 million NYC workers in-commute...

    # Commuting
    - id: total-nycworkerres
      isLinearNarrative: true
      transitionPrompt: 7% of the 4 million employed NYC residents out-commute...
    - id: total-nycresidentwork
      isLinearNarrative: true
      transitionPrompt: NYC in-commuter and resident workforces have grown...
    - id: total-nycworkerchange
      isLinearNarrative: true
      transitionPrompt: Manhattan workers mostly commute via transit...
    - id: mode-mnworkerres
      isLinearNarrative: true
      transitionPrompt: In-commuters to Non-Manhattan Boroughs mostly drive...
    - id: mode-nonmnworkerres
      isLinearNarrative: true
      transitionPrompt: NYC residents out-commuting for work mostly drive...
    - id: mode-nycresidentwork
      isLinearNarrative: true
      #transitionPrompt: End of Narrative Slideshow
