orderings:

  pages:
    - id: about

  maps:
    - id: intro
      hasNarrative: true
      hideFromMenu: true

    # People
    - id: total-population
      hasNarrative: true
    - id: population-density
      hasNarrative: true
    - id: population-change
      hasNarrative: true
    - id: net-population-change
      hasNarrative: true
    - id: foreign-born
      hasNarrative: true
    - id: prime-labor-force-gain
      hasNarrative: true

    # Housing
    - id: total-units
      hasNarrative: true
    - id: renter-owner
      hasNarrative: true
    - id: units-permitted
      hasNarrative: true
    - id: multifamily-permitted
      hasNarrative: true

    # Jobs
    - id: total-employment
      hasNarrative: true
    - id: private-employment-change
      hasNarrative: true

    # Balance
    - id: balance-housjobs00
      hasNarrative: true
    - id: balance-housjobs16
      hasNarrative: true
