orderings:

  pages:
    - id: about

  maps:
    - id: intro
      isLinearNarrative: true
      hideFromMenu: true
      transitionPrompt: 23 million people live in the NYC region...

    # People
    - id: total-population
      isLinearNarrative: true
      transitionPrompt: Our region is densest at the center...
    - id: population-density
      isLinearNarrative: true
      transitionPrompt: Population growth has shifted toward's the center...
    - id: population-change
      isLinearNarrative: true
      transitionPrompt: Population growth has shifted toward's the center...
    - id: net-population-change
      isLinearNarrative: true
      transitionPrompt: Growing areas are among the most diverse...
    - id: foreign-born
      isLinearNarrative: true
      transitionPrompt: Our region's labor force grew by 15%...
    - id: labor-force-gain
      isLinearNarrative: true
      transitionPrompt: Prime-age labor force grew mostly at the center...
    - id: prime-labor-force-gain
      isLinearNarrative: true
      transitionPrompt: Our region has 9 million homes...

    # Housing
    - id: total-units
      isLinearNarrative: true
      transitionPrompt: Rental housing is concentrated in NYC...
    - id: renter-owner
      isLinearNarrative: true
      transitionPrompt: Multifamily housing is concentrated in NYC...
    - id: units-by-structure
      isLinearNarrative: true
      transitionPrompt: NYC and NJ are building the majority of new housing...
    - id: units-permitted
      isLinearNarrative: true
      transitionPrompt: Most new housing was in multifamily buildings...
    - id: multifamily-permitted
      isLinearNarrative: true
      transitionPrompt: NYC is the hub of the largest U.S. metro economy...

    # Jobs
    - id: total-employment
      isLinearNarrative: true
      transitionPrompt: The distribution of jobs mirrors population patterns...
    - id: employment-by-sector
      isLinearNarrative: true
      transitionPrompt: Half of the region's office jobs are in NYC...
    - id: office-employment
      isLinearNarrative: true
      transitionPrompt: There are 2.7 million insitutional jobs in the region...
    - id: institutional-employment
      isLinearNarrative: true
      transitionPrompt: There are 1.7 million industrial jobs in the region...
    - id: industrial-employment
      isLinearNarrative: true
      transitionPrompt: There are 2.1 million local services jobs in the region...
    - id: localserve-employment
      isLinearNarrative: true
      transitionPrompt: Post-recession, NYC saw the majority of job gains...
    - id: private-employment-change
      isLinearNarrative: true
      transitionPrompt: The regional housing-jobs balance has shifted...

    # Balance
    - id: balance-housjobs00
      isLinearNarrative: true
      transitionPrompt: The regional housing-jobs balance has shifted...
    - id: balance-housjobs16
      isLinearNarrative: true
      transitionPrompt: The regional housing-jobs balance has shifted...
    - id: balance-housjobs0016
      isLinearNarrative: true
      transitionPrompt:
