orderings:

  pages:
    - id: about

  maps:
    - id: intro
      isLinearNarrative: true
      hideFromMenu: true
      transitionPrompt: 23 million people live in the NYC region...

    # People
    - id: total-population
      isLinearNarrative: true
      transitionPrompt: Our population is recentralizing...
    - id: population-density
      isLinearNarrative: true
      transitionPrompt: Learn about some subject in the next map
    - id: population-change
      isLinearNarrative: true
    - id: net-population-change
      isLinearNarrative: true
    - id: foreign-born
      isLinearNarrative: true
    - id: prime-labor-force-gain
      isLinearNarrative: true

    # Housing
    - id: total-units
      isLinearNarrative: true
    - id: renter-owner
      isLinearNarrative: true
    - id: units-permitted
      isLinearNarrative: true
    - id: multifamily-permitted
      isLinearNarrative: true

    # Jobs
    - id: total-employment
      isLinearNarrative: true
    - id: office-employment
      isLinearNarrative: true
    - id: institutional-employment
      isLinearNarrative: true
    - id: industrial-employment
      isLinearNarrative: true
    - id: localserve-employment
      isLinearNarrative: true
    - id: private-employment-change
      isLinearNarrative: true

    # Balance
    - id: balance-housjobs00
      isLinearNarrative: true
    - id: balance-housjobs16
      isLinearNarrative: true
    - id: balance-housjobs0016
      isLinearNarrative: true
